name: Go

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goarch: amd64
            goos: linux
            gobinary: ""
          - goarch: amd64
            goos: darwin
            gobinary: ""
          - goarch: amd64
            goos: windows
            gobinary: .exe
          - goarch: arm64
            goos: linux
            gobinary: ""
          - goarch: arm64
            goos: darwin
            gobinary: ""
          - goarch: arm64
            goos: windows
            gobinary: .exe
          - goarch: 386
            goos: linux
            gobinary: ""
          - goarch: 386
            goos: windows
            gobinary: .exe

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build binary
      run: CGO_ENABLED=0 go build -ldflags "-s -w" -o serve-swagger-ui${{ matrix.gobinary }} main.go && zip -v serve-swagger-ui-${{ matrix.goos }}-${{ matrix.goarch }}.zip serve-swagger-ui${{ matrix.gobinary }}
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      
    
      

